### ISSUE TITLE
Limitiertes Inventar?

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#12]
Soll der Spieler nur ein limitiertes Inventar haben, also nur eine bestimmte Anzahl an Items tragen können?

**Comment by Flummi3** [comment]
Der Spieler sollte ein unendlich großes Inventar haben, also kein limitiertes.

**Comment by Janonard** [comment]
Okay.

**Comment by WitchKing1999** [comment]
Ich stimme Flummi zu.
