### ISSUE TITLE
Speicherstände

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#15]
Wann und was soll im Spiel gespeichert werden? "Was" ist relativ einfach zu sagen: Statuswerte, Inventar, Level und die Questliste. "Wann" ist schon komplizierter:

Möglichkeit 1: Speicherpunkte
Wählen wir diese Methode, stellt sich mir noch die Frage, ob man die Speicherpunkte mehrfach oder nur einmal aktivieren kann.

Möglichkeit 2: Automatisch:
Nach jedem Levelwechsel, wird das Spiel gespeichert.

Welche Variante findet ihr besser?

**Comment by Flummi3** [comment]
Ich fände es besser, wenn man manuell speichern kann aber auch durch Gebietswechsel automatisch gespeichert wird.

**Comment by WitchKing1999** [comment]
Stimme zu!

**Comment by Janonard** [comment]
Ich habe noch eine Frage: Wenn der Spielstand gespeichert wird, soll der Alte überschrieben werden, oder wird ein neuer Spielstand angelegt? Soll es überhaupt mehrere Spielstände geben können?

**Comment by WitchKing1999** [comment]
2. Ja!
1. Man soll aussuchen ob man überschreiben kann oder einen neuen Speicherstand erstellen soll.
