### ISSUE TITLE
Skill-System

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#16]
@WitchKing1999: Wie weit bist du mit dem Skill-System?

**Comment by WitchKing1999** [comment]
Noch nicht fertig.
Wo sollte ich das nochmal reinmachen?

**Comment by Janonard** [comment]
In das Gameplay-Dokument [doc/Gameplay/Gameplay.md](../blob/master/doc/Gameplay/Gameplay.md). Bearbeite bitte dafür den Abschnitt "Erfahrungen sammeln". Wenn du möchtest, kannst du ihn auch umbennen.

**Comment by WitchKing1999** [comment]
Ist das Skillsystem nicht schon drinn?
Warum ist diese Issue noch auf?

**Comment by Janonard** [comment]
Stimmt, das ist schon drin.
