### ISSUE TITLE
Klassen - Magier

### ISSUE THREAD

**Issue by WitchKing1999** [Flumminard/Ambosia#19]
Als Magier braucht man Mana um magische Waffen zu benutzen.
Nun die Frage: nehmen wir auch "magischen Schaden" mit in das Skillsystem?
Ich finde schon, weil für mich ist Mana die Energie um einen Zauber auszuführen.

Der magische Schaden wäre sehr sinnvoll für "Mid- Game- Magier" , weil wenn man in magischen Schaden investiert hat, wenn man schon außreichend Mana hat macht man mit den
"Early- Game- Waffen" mehr Schaden und die brauchen nicht viel Mana, dass heißt, dass man schnell viel Schaden raushaut.

Das ist dann wieder Balancing aber ich denke jede Klasse sollte Vor- und Nachteile haben:

Krieger: Nahkampfschaden, Leicht verwundbar wegen Nahkampf (LP aufwendig wegen HP?) , Kampf ist leicht(= Guter Schaden, man muss nicht zielen)

Schütze: Fernkampfschaden, Goldaufwendig wegen Projektilen, Kampf ist sicher wegen Fernkampf.

Magier: Mana, magischer Schaden, LP aufwendig, Kampf ist sicher und leicht.
Leicht= Enormer Schaden dafür muss man gut zielen.

Wie ist eure Meinung?

**Comment by Janonard** [comment]
Ich sehe das so ähnlich, aber kosten deiner Auffassung nach auch Nahkampfwaffen Mana? Wenn dem so ist, sollte man "Mana" besser in "Energie" umbennen.

Ist des Minuszeichen im Titel ein Gedankenstrich oder ein Bindestrich?

**Comment by WitchKing1999** [comment]
1. Nein Waffen kosten kein Mana.
2. Gedankenstrich.

**Comment by Janonard** [comment]
Kannst du das in deinen nächsten PR rein nehmen?
