### ISSUE TITLE
Darstellung der Welt

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#2]
Die Frage ist simpel, ist aber verdammt schwierig zu beantworten: Sollen Sprites oder 3D-Modelle zur Darstellung der Welt genutzt werden?

Sprites sind einfacher zu erstellen und kosten wenig Resourcen. Wenn es aber zu Animationen oder Variationen kommt, müssen sie komplett neu erstellt werden.
3D-Modelle sind genau anders herum: Ein grundlegendes Modell zu erstellen, das auch noch gut aussieht, ist komplizierter, aber ist es einmal erstellt, kann es frei animiert oder modifiziert werden.

Diese Wahl zwischen 2D und 3D entscheidet aber auch darüber, welche Engine verwendet werden kann. Ich habe bisher mit cocos2d und Unreal Engine 4 experimentiert. cocos2d ist meiner Meinung nach eine solide 2D-Engine mit einer tollen Dokumentierung, allerdings hat sie spärliche bis gar keine 3D-Features und hat kaum die Möglichkeit, über grafische Editoren genutzt zu werden.
Unreal Engine 4 ist eine der leistungsstärksten 3D-Engines weltweit und verfügt über einen großartigen Editor, mit dem man allein ohne echte Programmierkenntnisse gute Spiele machen kann. Allerdings ist die Dokumentierung der Programmierschnittstelle gegenüber cocos2d deutlich schlechter und benötigt relativ gute Hardware. Dazu kommt, dass sie, als eine Art Gegenstück zu cocos2d, relativ schlechte 2D-Unterstützung hat.

Also fasse ich zusammen:
* Sprites sind einfach zu erstellen, aber schwer zu animieren; 3D-Modelle sind schwer zu erstellen, aber einfach zu animieren.
* Sprites benötigen weniger Leistung; 3D-Modelle sehen besser aus.
* cocos2d ist für 2D-Spiele geeignet; Unreal für 3D-Spiele.
* cocos2d ist gut zum programmieren; Unreal gut zum designen.

Was ist eurer Meinung nach die Bessere Wahl für Ambosia?

**Comment by WitchKing1999** [comment]
Ich kann nur sagen, dass ich der Designer bin deshalb würde ich Unreal nehmen, damit meine Arbeit für mich besser aussieht oder ich mehr zufrieden bin.

**Comment by Janonard** [comment]
Allerdings musst du dich dann in 3D-Modellierung und -Animation einarbeiten. Aber ansonsten stimme ich dir da zu.
Noch etwas: Mit der Unreal Engine geben wir auch die Option auf, Ambosia auch auf den Raspberry Pi zu bringen.

**Comment by Janonard** [comment]
Ich probiere mal, ein paar Argumente zusammenzubringen.
Die große Technik, die hinter Unreal steht, ist für uns nicht so wichtig, da wir sie sowieso nicht auschöpfen können. Allerdings stellt Unreal auch viel Technik zu Verfügung, die ich bei cocos selbst schreiben müsste.
3D-Modellieren ist deutlich komplizierter als Sprites zeichnen, allerdings sehen Modelle meistens besser aus. Am Anfang hatten wir allerdings festgelegt, dass Ambosia (bzw. damals noch "the Berry Quest") ein 2D-Spiel sein soll.
Der Hauptvorteil von Unreal gegenüber cocos sind aber die Editoren zum Erstellen und Bearbeiten von eigentlich Allem. Das fehlt cocos2d in weiten Teilen und vieles, was bei Unreal grafisch erledigt wird, wird bei cocos im C++-Quellcode festgelegt.
Es formen sich also zwei Probleme, wenn wir uns für 3D und damit für die Unreal Engine entscheiden sollten: Ambosia sollte eigentlich ein 2D-Spiel sein und wir müssten uns in 3D-Modellierung einarbeiten.
Das letzte Problem kannst nur du bewerten, @WitchKing1999, da du als Designer die größte Umstellung hast. Wenn du es dir zutraust, können wir ja ausprobieren, ob es mit Unreal in 3D funktioniert und im Notfall dann zu cocos wechseln.
Das erste Problem betrifft uns alle: Wollen wir wirklich den Design-Grundsatz "2D-Darstellung" einfach so über den Haufen werfen?

Ich bin auf eure Antworten gespannt.

**Comment by WitchKing1999** [comment]
Ich bin immmer noch für Unreal, weil ich mich mit Cocos nicht befasst habe und mit Unreal auch noch nicht aber wenn das Design bei Unreal besser/ "einfacher" ist dann entscheide ich mich dafür.

Ich bin letztendlich dafür, dass es immer noch 2D sein soll weil es schon so viele 3D RPGs gibt:
Skyrim, Cube World, Gothic, Witcher, Runescape, WoW, etc.
Bei 2D fällt mir nichts ein, dass heißt das es mal was neues wäre.

**Comment by Janonard** [comment]
Dein Argument verstehe ich nicht ganz: Das RPG-Genre wurde in 2D erfunden und die ersten großen RPGs sind in 2D: Ultima, Zelda, Final Fantasy I bis VI und Pokemon. Auf dem SNES und der PS1 gab es auch viele 2D-RPGs, dein Argument, dass wäre dann was neues, stimmt also nicht.
Deine Entscheidung Unreal mit 2D-Grafik zu verwenden, akzeptiere ich. Du bist der Designer.
Ich mache demnächst ein PR dazu.

**Comment by WitchKing1999** [comment]
Pokémon ist meiner Meinung kein RPG, Zelda stimme ich dir zu, Ultima und die alten Final Fantasy Teile kenne ich nur vom Namen her.
Was hält eigentlich @Flummi3 von dem ganzem?

**Comment by Janonard** [comment]
Ich habe noch eine Möglichkeit vergessen: 2,5 D! Hier wird die Umgebung in 3D dargestellt, aber die Figuren sind in 2D. Die Assets für die Umgebung kann man sich irgendwo zusammenkopieren, sodass Du @WitchKing1999 dich mehr auf die Wesen konzentrieren kannst.

**Comment by WitchKing1999** [comment]
Wir versuchen doch ein eigenes Spiel zu machen warum sollten wir, ich zitiere:
"Die Assets für die Umgebung kann man sich irgendwo zusammenkopieren"
Also entweder ganz oder garnicht und damit meine ich, dass ich sowohl Lust dazu habe die Wesen als auch den Hintergrund zu machen.

**Comment by Janonard** [comment]
Importieren von Assets ist nur eine Möglichkeit, um die Entwicklungsdauer zu verkürzen. Was du machst, ist dir überlassen.

Aber davon abgesehen: Wie findest du die Idee mit dem 2.5 D?

**Comment by Flummi3** [comment]
Das graphische wird dir überlassen @WitchKing1999.

Am 17. September 2015 um 19:08 schrieb Jan-Oliver Opdenhövel <
notifications@github.com>:

**Comment by WitchKing1999** [comment]
Ich müsste dazu erstmal ein Beispiel sehen aber ich denke, dass ich wie gesagt 3D besser finde aber mit 2,5D habe ich mich bis jetzt noch nicht befasst.

**Comment by Janonard** [comment]
Ich mach mal welche.

**Comment by Flummi3** [comment]
Agreed!

2015-09-18 7:16 GMT+02:00 Jan-Oliver Opdenhövel <notifications@github.com>:

**Comment by Janonard** [comment]
Fertig! [hier](https://github.com/Janonard/Ambosia-Test/releases/tag/0) ist es! (Zum beenden müsst ihr Alt+F4 nehmen)
So wie das 3D-Level stelle ich mir in etwa 2,5 D vor: Man läuft durch eine dreidimensionale Welt, in der die Charaktere zweidimensional sind. Das gibt es wirklich selten und währe ein wirkliches Alleinstellungsmerkmal.
Obwohl die Darstellung komplett anders ist, kann viel Gameplay-Basis sowohl in 2D als auch in 3D verwendet werden, die Option, von 3D auf 2D zu wechseln steht also fast immer offen.

Ich persönlich bin für 2,5D, da ich diese Darstellungsweise für ein Spiel sehr interressant finde. Wie sieht ihr das?

**Comment by WitchKing1999** [comment]
Wo zur Hölle sind die anderen Issues mit meinen tollen Ideen? :(

**Comment by Janonard** [comment]
Im Ordner /doc/Ideen.
Wie findest Du die Demo?

**Comment by Flummi3** [comment]
Finde die Demo gut, aber komme nicht in das "zweite Level". Der NPC läuft
gegen mich und weicht dann aus. Außerdem zeigt der Pfeil (eigener
Charakter) manchmal nach unten wenn man gegen eine Wand läuft.

Am 24. September 2015 um 07:14 schrieb Jan-Oliver Opdenhövel <
notifications@github.com>:

**Comment by Janonard** [comment]
Du musst selber (aktiv) in den NPC reinlaufen. Hast schon direkt einen Bug gefunden! :)

**Comment by Flummi3** [comment]
Bin aktiv in den NPC reingelaufen aber er ist nur an mir abgeprallt.

2015-09-25 20:11 GMT+02:00 Jan-Oliver Opdenhövel <notifications@github.com>:

**Comment by Janonard** [comment]
Das bisherige Ergebniss der Diskussion ist, dass wir mit Unreal Engine arbeiten wollen.
Die Wahl, in welcher Form Inhalte dargestellt werden, würde ich dann auf später verschieben, wenn die Inhalte erstellt werden. Wie seht ihr das?

**Comment by WitchKing1999** [comment]
Sehe ich genauso.

**Comment by Janonard** [comment]
OK, dann füge ich das in den nächsten PR von mir ein.
