### ISSUE TITLE
Arena-Modus?

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#21]
Mir ist heute eine nette Idee eingefallen: Warum beginnen wir Ambosia nicht mit einem Arena-Modus?
In diesem Arena-Modus befindet man sich, wie der Name schon sagt, in einer Arena, in der zufällig neue Monster spawnen, die dann Ausrüstung droppen, mit der man dann noch mehr Monster töten kann. Je länger man in der Arena durchhält, desto schwieriger wird es auch, die Monster zu besiegen. Optional könnte man auch Multiplayer-Features einfügen.

Aber wieso das Ganze? Die Story umzusetzen wird viel Zeit kosten, die Arena würde nicht so lange brauchen, wir würden also schneller ein vorzeigbares Ergebnis bekommen. Wenn sich dann ein paar Leute finden, denen die Arena gefällt, könnten die uns auch bei der Umsetzung der Story helfen. Außerdem können wir die Erfahrung, die wir mit der Arena sammeln, gebündelt in den Story-Modus stecken.

Wie findet ihr die Idee?

**Comment by WitchKing1999** [comment]
Für den Anfang ok.

**Comment by Janonard** [comment]
Was meinst du mit "Für den Anfang ok."?

**Comment by WitchKing1999** [comment]
Kann man machen.

**Comment by Janonard** [comment]
Fazit: Zuerst setzen wir den Arena-Modus für Version 0.X um und planen dabei im Hintergrund die Story von Version 1.X, die umgesetzt wird, wenn Version 0.X fertig ist. Einverstanden?

**Comment by WitchKing1999** [comment]
Ja
