### ISSUE TITLE
Mana-Regeneration

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#23]
Ich habe eine Frage: Soll es automatische Manaregeneration geben, und, wenn ja, wodurch soll sie festgelegt werden? Einerseits könnte das eine Fähigkeit des Spielers sein, andererseits auch durch Items bestimmt werden, oder sogar beides.

**Comment by WitchKing1999** [comment]
Ich finde man soll Manaregeneration haben, die man nur durch skillen von Mana bekommt.
-> Mehr Mana, mehr Regeneration. (Im endgame überdurchsnittlich aber nicht zu stark/ Siehe unten)
Wenn man keine Mana- Reg. hat ist der Magier zu schwer.
Wenn man Mana- Reg mit Items bekommen kann ist das zu stark und man braucht keine Tränke mehr.

**Comment by Janonard** [comment]
Aber Manatränke soll es geben?

**Comment by WitchKing1999** [comment]
Ja sie geben sofort eine bestimmte Menge an Mana so wie bei Terraria.
