### ISSUE TITLE
Genre

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#24]
Eigentlich ist ja klar, welches Genre "the Berry Quest" haben soll: 2D RPG. Das heisst, die Steuerung und die Darstellung ist ausschließlich zweidimensional und der Spieler spielt die Rolle des Haupthelden und muss sich ihr entsprechend im Spiel zurecht finden.
Ist das so richtig oder gibt es noch Einwände?

**Comment by WitchKing1999** [comment]
Reicht meiner Meinug nach.

**Comment by Janonard** [comment]
Eine Frage habe ich noch: Wie sollen die Kämpfe stattfinden: In Echtzeit oder rundenbasiert? Einerseits sind wir mit den Echtzeitkämpfen dem Vorbild Zelda näher, andererseits kommt bei rundenbasierten Kämpfen mehr Strategie zum Einsatz.

**Comment by WitchKing1999** [comment]
Wenn du mit Rundenbasiert ein ähnliches Prinzip wie bei Pokémon meinst, dann können wir ja bei Bosskämpfen rundenbasiert machen aber ansonnsten würde ich das echtzeit machen halt Zelda ähnlich.
Ich bin eher für Echtzeit. Das mit den Bosskämpfen ist nur eine Idee.

**Comment by Janonard** [comment]
Gut dann, wäre alles geklärt. Ich warte noch bis die Namesfrage in Issue #23 geklärt ist und fange dann mit dem Gamedesign-Dokument an.

**Comment by WitchKing1999** [comment]
Moooment!
Machen wir das mit den Bossen jetzt Echtzeit oder Rundenbasiert?

**Comment by Janonard** [comment]
Wenn wir das ganze Spiel in Echtzeit machen, sollten die Bosse auch in Echtzeit sein, ansonsten müsste man für die Bosse ein komplett anderes Gameplay lernen und üben.
