### ISSUE TITLE
Linzenzprobleme

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#24]
Als ich mich eben im Epic Launcher angemeldet habe, wurde mir die neue EULA von Epic angezeigt, die ich mir grob durchgelesen habe. Allerdings wird an einer Stelle gesagt, dass einige Linzenzen nich benutzt werden dürfen, dazu gehört auch die GPL. Das heißt, wir müssen jetzt wieder auf die MIT Linzenz umstellen.

**Comment by WitchKing1999** [comment]
Ok.
