### ISSUE TITLE
Platformen

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#26]
An sich haben wir ja entschieden, das Spiel für den PC zu entwickeln, aber welche Betriebssyteme wollen und können wir unterstützen?

Cocos unterstützt Windows, Mac und Linux, etwas anderes kommt also nicht in Frage (und wird wahrscheinlich auch keinen interressieren). Allerdings hat keiner von uns einen Mac, damit fällt das auch raus.

Das heißt, dass wir die Auswahl zwischen nur Windows, nur Linux oder beidem haben.

Ich persönlich wäre für nur Linux, weil dass die Entwicklung erheblich vereinfachen würde, aber wenn wir auch einen Windows-Build anbieten wollen, haben mir mehr potenzielle Kunden.
Was meint ihr?

**Comment by Flummi3** [comment]
Ich wäre dafür, dass wir alles erst für Linux machen und danach entscheiden, ob wir noch eine Version für Windows machen.

**Comment by Janonard** [comment]
OK, dann wäre das geklärt.

**Comment by WitchKing1999** [comment]
Stimme Flummi3 zu.

**Comment by Janonard** [comment]
Implementiert in Commit 52a35feda86b03e6277717655aa032561270e796
