### ISSUE TITLE
Planung

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#27]
Ich denke, es wäre ganz gut, einen Zeitplan zu haben, damit wir ungefähr abschätzen können, wie lange wir für das Projekt brauchen und damit geklärt ist, was wann gemacht wird. Am besten teilen wir das Projekt zuerst in mehrere Phasen ein:

* Concept:

Ausarbeitung der Story, der Design-, Gameplay-, und UI-Konzepte

* Source Alpha:

Umsetzung der Konzepte, allerdings wird noch kein großes Balancing durchgeführt, um zügig voran zu kommen. Da es für den Spieler keinen Sinn macht, das Spiel in diesem Stadium zu spielen, werden keine ausführbaren Builds zur Verfügung gestellt.

* Builded Beta:

Ausbalancieren des Spiels, eventuell hinzufügen von zusätzlichen Features wie Multiplayer-Modi o.ä. Während dieser Phase werden ausführbare Builds bereitgestellt und, wenn gewünscht, Portierungen auf Windows und/oder Mac durchgeführt.

* Release

Seid ihr soweit einverstanden?

**Comment by WitchKing1999** [comment]
Ja und ich denke für den Multiplayer sollten wir erstmal warten, weil ich für einen Multiplayer special features erwarte: Kurz gesagt Es soll kein Einzelspieler mit z.B. 2 Leuten sein.
Wir sollten uns mehr auf den Einzelspieler konzentrieren.
Ich bin soweit einverstanden, weil die Reihenfolge Sinn ergibt.

**Comment by Janonard** [comment]
OK, dann befinden wir uns jetzt in der "Concept" Phase.

**Comment by Janonard** [comment]
Ich denke, es wäre das Beste, wenn wir die Planung der einzelnen Phasen jeweils an ihren Beginn legen. Das macht die Planung deutlich flexibler. Außerdem würde ich die "Source Alpha" gerne in "Adding Alpha" umbennen, dann können wir nämlich die Abkürzungen "AA" und "BB" verwenden. So in Ordnung?

**Comment by WitchKing1999** [comment]
Abkürzung SA hört sich auch sehr seltsam an....

**Comment by Janonard** [comment]
Das war meine Absicht.
