### ISSUE TITLE
Ablauf der Konzept-Phase

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#28]
In der Konzept-Phase werden, wei der Name schon sagt, die Konzepte des Spieles entwickelt. In unserem Fall wären das: die Geschichte, die Zeichenstile, das Gameplay- und das UI-Konzept. Wer was macht ist auch klar: die Geschichte machen wir gemeinsam, die Zeichenstile kommen von @WitchKing1999, das UI-Konzept von @Flummi3 und das Gameplay von mir. Die einzige noch zu klärende Frage ist: In welcher Reihenfolge wird welches Konzept entwickelt? Hier sind drei Vorschläge von mir:

1.: Das Gameplay richtet sich nach der Story
Story
|------------- Zeichenstil
Gameplay
|
UI

2.: Die Story richtet sich nach dem Gameplay
Gameplay
|------------- UI
Story
|
Zeichenstil

3.: Story und Gameplay werden gleichzeitig entworfen
Story/Gameplay
|---Zeichenstil
UI

Die UI ist in jedem Fall von dem Gameplay und der Zeichenstil von der Story abhängig.
Nummer 3 hat den Vorteil, dass Story und Gameplay genauer aufeinander abgestimmt werden können, allerdings muss sich dafür mehr ausgetauscht werden, was den Fortschritt verlangsamen kann.

Welchen Vorschlag findet ihr am besten?

**Comment by Janonard** [comment]
Da keiner was schreibt, mach ich das jetzt. Also:

Ich bin für die Version 3, da diese die Konzeptphase deutlich verkürzen kann. Allerdings müssen die, die an der Story arbeiten, sich immer auf dem laufenden Halten, was gerade für das Gameplay geplant wird und umgekehrt.

Das Gameplay würde ich gerne selber planen, da ich es auch umsetzen muss und die Story sollten wir gemeinsam bei einem Treffen erstellen. Die Artconcepts werden am besten von @WitchKing1999 erstellt und wenn das Gameplay fertig ist, kann @Flummi3 die UI planen.

Was sagt ihr dazu?

**Comment by WitchKing1999** [comment]
Einverstanden!
