### ISSUE TITLE
Loot

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#30]
Ich wollte mich eben an die Implementierung von Loot setzen, da ist mir aufgefallen, dass wir keine genaue Regelung haben, wie der Loot überhaupt vergeben wird.

Eine Idee: Ist der letzte, der dem NPC Schaden zugefügt hat, der Spieler, geht der NPC alle seine Items durch und ermittelt anhand der Dropchance des Items, ob das Item gedropt werden soll oder nicht. Ist das der Fall, gibt der NPC dem Spieler dieses Item.

Was denkt ihr?

**Comment by Flummi3** [comment]
Finde ich gut, nur man müsste zusätzlich dazu beachten, dass dann von dem ganzen "Itempool" nur eine bestimmte Menge Items gedroppt (bzw. übergeben) werden und man nicht durch zu viel Glück ALLE Items des NPCs bekommt.

**Comment by WitchKing1999** [comment]
Meiner Meinung nach passiert folgendes:
-Held besiegt Gegner -> Gegner stirbt, Leiche liegt am Boden* -> liegt so lange am Boden,
 bis der Held in einem anderem Gebiet ist oder der Held die Leiche gelootet hat.
Leichen mit Quest- Items liegen so lange am Boden, bis sie gelootet wurden.
* Falls es teschnisch nicht möglich ist:
Beim sterben des Gegners bekommt der Held automatisch den Loot.

-Held erfüllt Quest -> Held gibt Quest beim Questgeber ab -> Questgeber gibt 100%igen Loot dem Helden

Zum Loot:
Jedem NPC ist eine bestimmte Anzahl an Items (Loot) festgelegt.
Jedoch sind einige Items seltener zu bekommen als andere.
Z.B. der Moonlord von Terraria hat eine 100%ige Dropchance von Heiltränken, Erz
und der Portal Gun. Aber nur eine 14,29%ige Dropchance auf die Maske.

Ich stimme Flummi zu!

**Comment by Janonard** [comment]
An die Problematik mit dem kompletten Loot hab ich noch garnicht gedacht, ich mach mir da später nochmal Gedanken, ihr könnt euch aber auch was ausdenken (vor allem @Flummi3).

@WitchKing1999: Ich bin eher dafür, dass der Loot automatisch verteilt wird, da du ansonsten für jeden NPC eine Todespose erstellen musst, das würde dann zuviel Zeit kosten, außerdem ist es technisch sogar einfacher den Loot automatisch zu verteilen.

Was die Quests angeht stimme ich dir zu, allerdings ist das nachher eine Entscheidung des Spieldesigns und nicht der Technik, darum brauchen wir uns jetzt also nicht zu kümmern.

**Comment by Janonard** [comment]
Eigentlich brauchen wir uns keine Sorgen zu machen, dass der Spieler alles gedropt bekommt: Die Wahrscheinlichkeit dafür ist viel zu gering:

Stellen wir uns als Beispiel einen NPC mit folgenden Items vor, die Dropchance steht in Klammern hinter den Namen:

* Schwert (1/4)
* Rüstung (1/4)
* Heiltrank (1/4)
* Geld (1/4)
* Müll (1/2)

Wenn man die Chancen miteinander multipliziert, erhält man die Wahrscheinlichkeit, alles zu erhalten und die ist in unserem Fall (1/512), oder in Prozent: 0.195.
Es ist also fast Unmöglich, alles zu bekommen, daher brauchen wir uns darum keine Sorgen zu machen.

**Comment by WitchKing1999** [comment]
Naja aber den Müll musst du abziehen!

**Comment by Janonard** [comment]
OK, wenn du den Müll abziehst hast du immernoch 0,3%, es ist also immernoch fast unmöglich, alles zu bekommen. Außerdem wären diese Items relativ low-level.

**Comment by WitchKing1999** [comment]
Und bei High- Level- NPCs ?
Außerdem finde ich sollte man auf jeden Fall (100%) eine Waffe gedroped bekommen.
Man kann ja auch einigen NPCs mehrere Waffen geben, nur halt mit unterschiedlichen Dropchancen.

**Comment by Janonard** [comment]
Nochmal: Das sind Designentscheidungen, die die Technik nicht beeinflussen. Mit der Rechnung wollte ich zeigen, dass wir uns, selbst bei diesen hohen Dropchancen, nicht darum kümmern müssen, dass nicht alles gedropt wird. Wenn du findest, dass bei High-Level-NPCs auf jeden Fall ein Schwert gedropt werden muss, ist das absolut in Ordnung, aber dafür muss die Programmierung nicht angepasst werden.

**Comment by WitchKing1999** [comment]
Das mit den Waffendropchancen war eigentlich auf ALLE NPCs bezogen! (Nur Humanoide NPCs)

**Comment by Janonard** [comment]
Eine Frage habe ich noch, was den Loot-Algorythmus angeht: Soll bei gestackten Items die gesamte Stack-Größe übernommen werden, oder soll jedes Element des Stacks einzeln ausgeworfen werden? Ein Beispiel: Ein NPC hat ein Pfeil-Bündel mit dem Stack 30, das gedropt werden soll. Soll jetzt einfach ein Pfeil-Bündel mit dem Stack 30 gedropt werden oder soll für alle 30 Pfeile berechnet werden, ob sie gedropt werden?

**Comment by WitchKing1999** [comment]
Alles soll gedroppt werden und beim Einsammeln soll man endscheiden wie viel man nimmt.
Z.B. Auf einem Haufen liegen 2 Helme 3 Schwerter und 30 Pfeile.
Da kann man endscheiden, dass man 30 Pfeile nimmt aber nur 2 Schwerter und 1 Helm.

**Comment by Janonard** [comment]
Wieso? Die Items kann man doch bei Händler verscherbeln und das Inventar ist auch unendlich. Warum sollte man also etwas nicht mitnehmen?

**Comment by WitchKing1999** [comment]
Frage falsch verstanden....
