### ISSUE TITLE
Bewegungsmodell

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#30]
Ich habe mir schon einige Gedanken zur Spielsteuerung gemacht und dabei die der absoluten Grundlage angefangen: dem Laufen. In meinem bisherigen Modell sind sowohl Wände als auch Spielfiguren 32*32 Pixel groß und die Spielfiguren machen flüssige 16-Pixel-Schritte. Die einzigen möglichen Bewegungen sind vorwärts, rückwärts, links und rechts.

Wer das Ganze mal ausprobieren möchte, kann das Paket [hier](https://github.com/Janonard/Ambosia-gameplaydemo/releases/tag/v0.0.0) bekommen. Findet ihr das Modell so gut. Mit etwas Zeit könnte ich auch noch diagonale Bewegungen hinzufügen. Mehrere Ebenen mit Treppen dazwischen kommen erst noch später, das ist etwas komplizierter.

**Comment by Janonard** [comment]
Update:
Ich habe versucht, diagonale Bewegungen einzubauen, aber es ging nicht: Für Cocos kann immer nur eine Taste gedrückt sein, aber für d. Bewegungen müssen zwei Tasten gedrückt werden.

**Comment by Janonard** [comment]
Da ihr nicht antwortet, nehme ich jetzt an, dass ihr nichts gegen den Vorschlag habt. Ich glaube, ich sollte in Zukunft weniger Fragen sondern mehr machen.

**Comment by WitchKing1999** [comment]
Diagonal wäre toll, muss aber nicht sein.

**Comment by Janonard** [comment]
Ich lasse es in der Planung offen, ob es Diagonalbewegung gibt oder nicht.
