### ISSUE TITLE
Wie viele Ringe kann man tragen?

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#31]
Eine kleine Frage: Wie viele Ringe soll man tragen können?

**Comment by WitchKing1999** [comment]
Sehr gute Frage!
In den meisten RPGs kann man nur 2 Ringe tragen.
Ist eine gute Zahl nur bringen wir Handschuhe ins Spiel?
Wenn ja dann würde ich auch sagen 2 aber wenn nein dann bin ich der Meinung 3,
weil 4 zu viel Platz wegnehmen würde und an einer Hand kann man mehr Ringe (2) tragen während an der anderen das Kämpfen mit 2 Ringen schwerer wäre.
Und wenn wir Handschuhe reinnehmen muss man sich für 2 Ringe oder "Ein Paar Handschuhe" endscheiden.

Ich bin der Meinung wir bringen erstmal 2 Ringe ins Spiel und
dann kann man immer noch diskutieren.

**Comment by Janonard** [comment]
OK, zwei Ringe. Ich packs in meinen nächsten PR rein!
