### ISSUE TITLE
pull request-Abläufe

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#4]
Ich habe mir mal ein paar andere Open-Source-Projekte angeguckt und habe bemerkt, dass es fast immer festgeschriebene Abläufe gibt, wie neue Inhalte in das Repository eingefügt werden.

Ich glaube, wir brauchen das auch. Einfach nur um klar zu haben, wer was machen muss.
Wie sieht ihr das? Erklärt sich jemand bereit, sich da was auszudenken?

**Comment by WitchKing1999** [comment]
Wir wissen doch, wer was machen muss.  Oder nicht?

**Comment by Janonard** [comment]
Es geht mir vor allem darum das es überhaupt festgelegt ist, wer was in welchen Abläufen macht. Mündliche Absprachen haben die Eigenschaft, vergessen oder verändert zu werden und keiner was dann mehr was er machen soll. Wenn einmal ein allgemeiner Ablauf erstellt wurde, läuft dann auch einiges schneller ab. Und was ist, wenn sich noch jemand uns anschließen oder sich ein Bild von unserer Arbeit machen will? Dann können wir vorzeigen, in welcher Art wir dieses Projekt führen.
Ein kronkreter Fall: Wie viel Zeit hat man, um auf einen PR zu antworten und muss man überhaupt antworten. Wir haben da sehr unterschiedliche Ansichten, über die wir uns Austauschen sollten.

**Comment by Janonard** [comment]
Formuliere doch mal bitte aus, wer was macht und wie man was hier beitragen kann.

**Comment by Janonard** [comment]
Ich habe in den Ferien vor, rel. viel hochzuladen. Kann ich dann für die Ferienzeit meine PRs mergen, wenn nach 24 Stunden niemand geantwortet hat?

**Comment by Flummi3** [comment]
Ja von meiner Seit aus darfst du das.

Am 3. Oktober 2015 um 23:37 schrieb Jan-Oliver Opdenhövel <
notifications@github.com>:
