### ISSUE TITLE
Backgroundstory von Ambosiafork in Ambosia

### ISSUE THREAD

**Issue by WitchKing1999** [Flumminard/Ambosia#40]
Da die Backgroundstory in meinem Fork, welche unter
doc ->Background- Story zu finden ist, ja fertig ist könnte sie doch in Flumminard/Ambosia kopiert werden in doc ->Sory.
Wenn ich das machen soll bitte ich dich, Jan, mir zu sagen wie das geht.
Ansonnsten würde ich dich bitten auf meinen Vorschlag einzugehen.

**Comment by Janonard** [comment]
@WitchKing1999 Verschiebe einfach die Datei in den Ordner, den du haben möchtest, lade das hoch und erstelle einen Pullrequest. Entweder sorgt Git sich darum, dass das passt, oder ich mach es.
