### ISSUE TITLE
Geld-System

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#6]
Von wem soll es Geld geben?
Welche Währungen soll es geben?
Wie sollen sie heißen?

**Comment by WitchKing1999** [comment]
Es soll nur eine Währung geben, die man klasisch Gold nennen könnte.
Ich finde man bekommt Geld als Questbelohnung, wenn man irgendwo welches findet oder beim töten von humanoiden Wesen (Menschen, Goblins, Orcs, Elfen, usw.) -> Loot.

Meiner Meinung nach soll es auch nur eine "Geldklasse" geben, dass heißt das es nur eine Einheit gibt und kein Silber oder Kupfer zum Beispiel.

**Comment by Janonard** [comment]
OK, dann wär das geklärt.
