### ISSUE TITLE
Crafting

### ISSUE THREAD

**Issue by Janonard** [Flumminard/Ambosia#7]
Soll es Crafting geben?

**Comment by WitchKing1999** [comment]
Ich finde schon, aber es soll auf keinen Fall den Schwerpunkt, des Spiels tragen.
Wenn man Tränke aus Pflanzen herstellen könnte fänd ich toll, allerdings wäre das zu einfach und man könnte deshalb ein Talent (Tränke brauen) einfügen, dass geht aber alles in eine komplexe Richtung.
Man könnte auch Loot zu jemanden hinbringen, der daraus für Geld etwas herstellt.

**Comment by Janonard** [comment]
Die letzte Idee finde ich gut. Das würde ohne größeren Mehraufwand ein bisschen Craftingsystem bieten. Zur Umsetzung müsste man nämlich nur einen Händler einrichten, der mehrere Gegenstände entgegennimmt, also Item 1, 2 und das Geld, und dann im Gegenzug das "gecraftete" Item gibt. Finde ich gut!
