### ISSUE TITLE
Wann spawnen Kreaturen

### ISSUE THREAD

**Issue by WitchKing1999** [Flumminard/Ambosia#9]
Wie machen wir das mit dem Spawnen von Kreaturen?

Einige spawnen nur, nachdem man z.B. den Quest bekommen hat: Töte den besonderen Mondwolf.
Nachdem man einen solchen Quest bekommen hat spawnt die Kreatur in einem Gebiet.
Wenn man die Kreatur getötet hat ist der Quest erledigt und der besondere(!) Mondwolf wird nie wieder spawnen.

Aber wie machen wir das mit dem (fast) open- World- Prinzip?
Ich finde immer wenn man ein Kartenteil bekommen hat spawnen überall neue Kreaturen weil wenn man das einfach so macht, dass wenn man aus der Sichtweise der Spawnorte ist wieder neue Kreaturen spawnen kann man sich ja sehr leicht leveln.

Wie findet ihr das?

**Comment by Janonard** [comment]
Meinst du es so, dass man,  wenn man das Spiel durch hat, die Welt ausgerottet hat? Wenn die Wesen nicht neuspawnen, wird das nämlich passieren. Das sollte meiner Meinung nach verhindert werden. Das zu leichte Leveln kann man verhindern, in dem man einfach die benötigten XP hoch und/oder die gegebenen XP runter setzt.
Was die "special mobs" angeht, stimme ich dir zu, dass die Mobs nach dem Töten nicht neu spawnen. Wenn man das Spiel richtig hart machen möchte, kann man die special Mobs auch schon vorher spawnen lassen. Wenn man die dann tötet, könnte man dann die Quest nicht mehr machen.

**Comment by WitchKing1999** [comment]
Nein Ich finde nicht, dass die spezielen Kreaturen vorher spawnen nimmt einen den Spaß.
Aber wann werden die Kreaturen denn jetzt spawnen?

**Comment by Janonard** [comment]
Wenn du von normalen Kreaturen sprichst, würde ich vorschlagen, dass sie automatisch nachspawnen, damit man sie dann töten kann. Allerdings müssen dann die benötigten und die abgegebenen XP so balanciert werden, dass man nicht überlevelt.

**Comment by Flummi3** [comment]
Ich bin der Meinung, dass die Kreaturen nachspawnen sollten, wenn man das für die Kreaturen spezielle Gebiet betritt. Also, dass man nicht nur im Kreis rennen muss um alles zu töten um zu leveln sondern sich auch in Welt bewegen muss. Das würde das Balancing auch leichter machen, weil einzelne Kreaturen dann ein bisschen mehr "XP" abgeben können. @Janonard das "überleveln ist ja eigentlich erwünscht solange man dafür die nötige Geduld aufbringen kann. Es gibt sehr viele individuelle Spielstyles, welche auch aufs stumpfe leveln ausgeleggt sein können.

**Comment by Janonard** [comment]
@Flummi3: Man kann ja auch die Respawnzeiten hochstellen. Dann Braucht man fürs Warten genauso lange wie für einen Levelwechsel. Das kommt dann am Ende aufs selbe hinaus.

**Comment by Janonard** [comment]
Also: Im großen und Ganzen sind wir uns einig, dass normale NPCs neuspawnen. Die Wahl liegt nurnoch zwischen dem automatischen Respawnen und dem Respawn beim Laden des Levels.
Ich bin für das automatische Respawnen, da dass am wenigsten nervt, dafür muss dann der Ertrag eines Kills heruntergesetzt werden. Wie seht ihr das?
